[package]
name = "pnc-rs"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "pnc"

[[bin]]
name = "pnc-tcphashmap-node"

[lib]
name="libpnc"

[dependencies]
bincode = "1.3"
byteorder = "1.5"
rayon = "1.10"
crossbeam-channel = "0.5"
log = "0.4"
